# Generated by Django 3.1 on 2022-12-14 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moshin',
            name='rang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rang'),
        ),
    ]
